// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubtglqxafwjrmwkieloe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVidGdscXhhZndqcm13a2llbG9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDU1NjAsImV4cCI6MjA2MTI4MTU2MH0.jvmTzAzeoXSnMaKwzNs6hXnqDlhIq7x4BPg0G3xd6pw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);